/* Generated By:JavaCC: Do not edit this line. CarregaArqConstants.java */
package ispd.CarregaArqTexto;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CarregaArqConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RR = 1;
  /** RegularExpression Id. */
  int MAQ = 2;
  /** RegularExpression Id. */
  int VAZIO = 3;
  /** RegularExpression Id. */
  int LMAQ = 4;
  /** RegularExpression Id. */
  int REDE = 5;
  /** RegularExpression Id. */
  int INET = 6;
  /** RegularExpression Id. */
  int FPLTF = 7;
  /** RegularExpression Id. */
  int CARGA = 8;
  /** RegularExpression Id. */
  int TRACE = 9;
  /** RegularExpression Id. */
  int MESTRE = 10;
  /** RegularExpression Id. */
  int RANDOM = 11;
  /** RegularExpression Id. */
  int POISSON = 12;
  /** RegularExpression Id. */
  int ESCRAVO = 13;
  /** RegularExpression Id. */
  int CLUSTER = 14;
  /** RegularExpression Id. */
  int CONECTA = 15;
  /** RegularExpression Id. */
  int MAQUINA = 16;
  /** RegularExpression Id. */
  int TWOSTAGE = 17;
  /** RegularExpression Id. */
  int WORKQUEUE = 18;
  /** RegularExpression Id. */
  int EXPONENCIAL = 19;
  /** RegularExpression Id. */
  int especial = 20;
  /** RegularExpression Id. */
  int identificador = 21;
  /** RegularExpression Id. */
  int inteiro = 22;
  /** RegularExpression Id. */
  int flutuante = 23;
  /** RegularExpression Id. */
  int invalido = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"RoundRobin\"",
    "\"MAQ\"",
    "\"---\"",
    "\"LMAQ\"",
    "\"REDE\"",
    "\"INET\"",
    "\"FPLTF\"",
    "\"CARGA\"",
    "\"TRACE\"",
    "\"MESTRE\"",
    "\"RANDOM\"",
    "\"POISSON\"",
    "\"ESCRAVO\"",
    "\"CLUSTER\"",
    "\"CONECTA\"",
    "\"MAQUINA\"",
    "\"TWOSTAGE\"",
    "\"WORKQUEUE\"",
    "\"EXPONENCIAL\"",
    "<especial>",
    "<identificador>",
    "<inteiro>",
    "<flutuante>",
    "\"\\n\"",
    "\" \"",
    "\"\\t\"",
    "\"\\b\"",
    "<token of kind 28>",
    "<invalido>",
  };

}
