/* ==========================================================
 * iSPD : iconic Simulator of Parallel and Distributed System
 * ==========================================================
 *
 * (C) Copyright 2010-2014, by Grupo de pesquisas em Sistemas Paralelos e Distribuídos da Unesp (GSPD).
 *
 * Project Info:  http://gspd.dcce.ibilce.unesp.br/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * [Oracle and Java are registered trademarks of Oracle and/or its affiliates. 
 * Other names may be trademarks of their respective owners.]
 *
 * ---------------
 * JSobre.java
 * ---------------
 * (C) Copyright 2014, by Grupo de pesquisas em Sistemas Paralelos e Distribuídos da Unesp (GSPD).
 *
 * Original Author:  Denison Menezes (for GSPD);
 * Contributor(s):   -;
 *
 * Changes
 * -------
 * 
 * 09-Set-2014 : create class. Version 2.0;
 *
 */
package ispd.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author denison
 */
public class JSobre extends javax.swing.JDialog {

    /**
     * Creates new form JSobre
     */
    public JSobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            this.htmlLicense.setPage(JSobre.class.getResource("html/License.html"));
            this.htmlDevelopers.setPage(JSobre.class.getResource("html/Developers.html"));
        } catch (IOException ex) {
            Logger.getLogger(JSobre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        htmlDevelopers = new ispd.gui.auxiliar.HtmlPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        htmlLicense = new ispd.gui.auxiliar.HtmlPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About iSPD");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ispd/gui/imagens/Logo_iSPD_128.png"))); // NOI18N

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel2.setText("<html>    <body>     <p  style=\"margin-left: 20px;\">The <strong>\"iSPD : iconic Simulator of Parallel and Distributed System\"</strong><br/> was developed and supported by<br/> </p>    <p style=\"margin-left: 50px;\">Instituto de Biociências, Letras e Ciências Exatas,</b></br>     <p style=\"margin-left: 50px;\">UNESP - Univ Estadual Paulista, campus de São José do Rio Preto,</b></br>     <p style=\"margin-left: 50px;\">Departamento de Ciências de Computação e Estatística (DCCE),</b></br>     <p style=\"margin-left: 50px;\">Laboratório do Grupo de Sistemas Paralelos e Distribuídos (GSPD).</b></br>     </body> </html>");
        jTabbedPane1.addTab("About", jLabel2);

        htmlDevelopers.setText("");
        jScrollPane1.setViewportView(htmlDevelopers);

        jTabbedPane1.addTab("Developers", jScrollPane1);

        jScrollPane2.setViewportView(htmlLicense);

        jTabbedPane1.addTab("License", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 194, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ispd.gui.auxiliar.HtmlPane htmlDevelopers;
    private ispd.gui.auxiliar.HtmlPane htmlLicense;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
