/* ==========================================================
 * iSPD : iconic Simulator of Parallel and Distributed System
 * ==========================================================
 *
 * (C) Copyright 2010-2014, by Grupo de pesquisas em Sistemas Paralelos e Distribuídos da Unesp (GSPD).
 *
 * Project Info:  http://gspd.dcce.ibilce.unesp.br/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * [Oracle and Java are registered trademarks of Oracle and/or its affiliates. 
 * Other names may be trademarks of their respective owners.]
 *
 * ---------------
 * JUsuarios.java
 * ---------------
 * (C) Copyright 2014, by Grupo de pesquisas em Sistemas Paralelos e Distribuídos da Unesp (GSPD).
 *
 * Original Author:  Denison Menezes (for GSPD);
 * Contributor(s):   -;
 *
 * Changes
 * -------
 * Created on 01/06/2011
 * 09-Set-2014 : Version 2.0;
 *
 */
package ispd.gui;

import java.util.HashMap;
import java.util.HashSet;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Janela usada para adicionar e remover os usuarios da simulação modelada
 * @author denison
 */
public class JUsuarios extends javax.swing.JDialog {

    private ResourceBundle palavras;

    /** Creates new form ControleUsuarios */
    public JUsuarios(java.awt.Frame parent, boolean modal, HashSet<String> usuarios, ResourceBundle palavras) {
        super(parent, modal);
        this.usuarios = new Vector<String>(usuarios);
        this.palavras = palavras;
        initComponents();
        jListUsers.setListData(this.usuarios);
    }

    public HashSet<String> getUsuarios(){
        HashSet<String> ret = new HashSet<String>(usuarios);
        return ret;
    }
    
    public JUsuarios(java.awt.Frame parent, boolean modal, HashSet<String> usuarios, ResourceBundle palavras, HashMap<String, Double> perfil) {
        super(parent, modal); 
        this.usuarios = new Vector<Vector>();
        this.perfis = new Vector<String>();
        this.perfis.add("Users");
        this.perfis.add("Limite de Consumo (Porcentagem do consumo da porção)");
        for (String usuario : usuarios) {
            Vector user = new Vector<String>();
            user.add(usuario);
            user.add(perfil.get(usuario));
            this.usuarios.add(user);
        }
        this.usuario = usuarios;
        this.palavras = palavras;
        initComponents();
    }

    public HashMap<String,Double> getLimite(){
        HashMap<String,Double> ret = new HashMap<String,Double>();
        for (Vector user : usuarios) {
            ret.put(user.get(0).toString(), Double.parseDouble(user.get(1).toString()));
        }
        return ret;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jScrollPaneLista = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(palavras.getString("Manage Users")); // NOI18N
        setResizable(false);

        jToolBar.setFloatable(false);

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ispd/gui/imagens/insert-object.png"))); // NOI18N
        jButtonAdicionar.setText(palavras.getString("Add")); // NOI18N
        jButtonAdicionar.setFocusable(false);
        jButtonAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdicionar.setMaximumSize(new java.awt.Dimension(45, 45));
        jButtonAdicionar.setMinimumSize(new java.awt.Dimension(45, 45));
        jButtonAdicionar.setPreferredSize(new java.awt.Dimension(45, 45));
        jButtonAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonAdicionar);

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ispd/gui/imagens/window-close.png"))); // NOI18N
        jButtonRemover.setText(palavras.getString("Remove")); // NOI18N
        jButtonRemover.setFocusable(false);
        jButtonRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRemover.setMaximumSize(new java.awt.Dimension(45, 45));
        jButtonRemover.setMinimumSize(new java.awt.Dimension(45, 45));
        jButtonRemover.setPreferredSize(new java.awt.Dimension(45, 45));
        jButtonRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonRemover);

        jListUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, palavras.getString("Users"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jListUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneLista.setViewportView(jListUsers);

        jButtonOk.setText(palavras.getString("OK")); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jTable1.setModel(new DefaultTableModel(this.usuarios,this.perfis){ public boolean isCellEditable(int rowIndex, int columnIndex) {
            return true;
        }});
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneLista, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneLista, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOk)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        String add = JOptionPane.showInputDialog(this, palavras.getString("Enter the name"), palavras.getString("Add"), JOptionPane.QUESTION_MESSAGE);
        if(!usuarios.contains(add) && !add.equals("")){
            usuarios.add(add);
            jListUsers.setListData(usuarios);
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        if (!jListUsers.isSelectionEmpty()) {
            String aux = this.jListUsers.getSelectedValue().toString();
            int escolha = JOptionPane.showConfirmDialog(this, palavras.getString("Are you sure want delete this user:") + aux, null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (escolha == JOptionPane.YES_OPTION) {
                usuarios.remove(aux);
                jListUsers.setListData(usuarios);
            }
        } else {
            JOptionPane.showMessageDialog(this, palavras.getString("A user should be selected"));
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JList jListUsers;
    private javax.swing.JScrollPane jScrollPaneLista;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
    private Vector<String> usuarios;
}
