/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Usuarios.java
 *
 * Created on 01/06/2011, 12:47:59
 */

package ispd.gui;

import java.util.HashSet;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 * Janela usada para adicionar e remover os usuarios da simulação modelada
 * @author denison_usuario
 */
public class JUsuarios extends javax.swing.JDialog {

    private ResourceBundle palavras;

    /** Creates new form ControleUsuarios */
    public JUsuarios(java.awt.Frame parent, boolean modal, HashSet<String> usuarios, ResourceBundle palavras) {
        super(parent, modal);
        this.usuarios = new Vector<String>(usuarios);
        this.palavras = palavras;
        initComponents();
        jListUsers.setListData(this.usuarios);
    }

    public HashSet<String> getUsuarios(){
        HashSet<String> ret = new HashSet<String>(usuarios);
        return ret;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jScrollPaneLista = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(palavras.getString("Manage Users")); // NOI18N
        setResizable(false);

        jToolBar.setFloatable(false);

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ispd/gui/imagens/insert-object.png"))); // NOI18N
        jButtonAdicionar.setText(palavras.getString("Add")); // NOI18N
        jButtonAdicionar.setFocusable(false);
        jButtonAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdicionar.setMaximumSize(new java.awt.Dimension(45, 45));
        jButtonAdicionar.setMinimumSize(new java.awt.Dimension(45, 45));
        jButtonAdicionar.setPreferredSize(new java.awt.Dimension(45, 45));
        jButtonAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonAdicionar);

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ispd/gui/imagens/window-close.png"))); // NOI18N
        jButtonRemover.setText(palavras.getString("Remove")); // NOI18N
        jButtonRemover.setFocusable(false);
        jButtonRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRemover.setMaximumSize(new java.awt.Dimension(45, 45));
        jButtonRemover.setMinimumSize(new java.awt.Dimension(45, 45));
        jButtonRemover.setPreferredSize(new java.awt.Dimension(45, 45));
        jButtonRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonRemover);

        jListUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, palavras.getString("Users"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jListUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneLista.setViewportView(jListUsers);

        jButtonOk.setText(palavras.getString("OK")); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneLista, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneLista, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOk)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        String add = JOptionPane.showInputDialog(this, palavras.getString("Enter the name"), palavras.getString("Add"), JOptionPane.QUESTION_MESSAGE);
        if(!usuarios.contains(add) && !add.equals("")){
            usuarios.add(add);
            jListUsers.setListData(usuarios);
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        if (!jListUsers.isSelectionEmpty()) {
            String aux = this.jListUsers.getSelectedValue().toString();
            int escolha = JOptionPane.showConfirmDialog(this, palavras.getString("Are you sure want delete this user:") + aux, null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (escolha == JOptionPane.YES_OPTION) {
                usuarios.remove(aux);
                jListUsers.setListData(usuarios);
            }
        } else {
            JOptionPane.showMessageDialog(this, palavras.getString("A user should be selected"));
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JList jListUsers;
    private javax.swing.JScrollPane jScrollPaneLista;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
    private Vector<String> usuarios;
}
