/* Generated By:JavaCC: Do not edit this line. InterpretadorConstants.java */
/* ==========================================================
 * iSPD : iconic Simulator of Parallel and Distributed System
 * ==========================================================
 *
 * (C) Copyright 2010-2014, by Grupo de pesquisas em Sistemas Paralelos e Distribuídos da Unesp (GSPD).
 *
 * Project Info:  http://gspd.dcce.ibilce.unesp.br/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * [Oracle and Java are registered trademarks of Oracle and/or its affiliates. 
 * Other names may be trademarks of their respective owners.]
 *
 * (C) Copyright 2014, by Grupo de pesquisas em Sistemas Paralelos e Distribuídos da Unesp (GSPD).
 *
 * Original Author:  Denison Menezes (for GSPD);
 * Contributor(s):   -;
 *
 * Changes
 * -------
 * 
 * 09-Set-2014 : Version 2.0;
 *
 */
package ispd.arquivo.interpretador.gerador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InterpretadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SCHEDULER = 1;
  /** RegularExpression Id. */
  int STATIC = 2;
  /** RegularExpression Id. */
  int DYNAMIC = 3;
  /** RegularExpression Id. */
  int TASK = 4;
  /** RegularExpression Id. */
  int ENTRY = 5;
  /** RegularExpression Id. */
  int DISPACTH = 6;
  /** RegularExpression Id. */
  int COMPLETED = 7;
  /** RegularExpression Id. */
  int TIME = 8;
  /** RegularExpression Id. */
  int INTERVAL = 9;
  /** RegularExpression Id. */
  int RANDOM = 10;
  /** RegularExpression Id. */
  int FIFO = 11;
  /** RegularExpression Id. */
  int CRESCENT = 12;
  /** RegularExpression Id. */
  int DECREASING = 13;
  /** RegularExpression Id. */
  int RESOURCE = 14;
  /** RegularExpression Id. */
  int RESTRICT = 15;
  /** RegularExpression Id. */
  int TASKPER = 16;
  /** RegularExpression Id. */
  int USER = 17;
  /** RegularExpression Id. */
  int tTamComp = 18;
  /** RegularExpression Id. */
  int tTamComu = 19;
  /** RegularExpression Id. */
  int tNumTarSub = 20;
  /** RegularExpression Id. */
  int tNumTarConc = 21;
  /** RegularExpression Id. */
  int tPoderUser = 22;
  /** RegularExpression Id. */
  int tTempSubm = 23;
  /** RegularExpression Id. */
  int rPodeProc = 24;
  /** RegularExpression Id. */
  int rLinkComu = 25;
  /** RegularExpression Id. */
  int rtamCompTar = 26;
  /** RegularExpression Id. */
  int rtamComuTar = 27;
  /** RegularExpression Id. */
  int numTarExec = 28;
  /** RegularExpression Id. */
  int mflopProce = 29;
  /** RegularExpression Id. */
  int mult = 30;
  /** RegularExpression Id. */
  int div = 31;
  /** RegularExpression Id. */
  int sub = 32;
  /** RegularExpression Id. */
  int add = 33;
  /** RegularExpression Id. */
  int lparen = 34;
  /** RegularExpression Id. */
  int rparen = 35;
  /** RegularExpression Id. */
  int inteiro = 36;
  /** RegularExpression Id. */
  int real = 37;
  /** RegularExpression Id. */
  int nome = 38;
  /** RegularExpression Id. */
  int invalido = 50;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecoment = 1;
  /** Lexical state. */
  int singlelinecoment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"SCHEDULER\"",
    "\"STATIC\"",
    "\"DYNAMIC\"",
    "\"TASK\"",
    "\"ENTRY\"",
    "\"DISPACTH\"",
    "\"COMPLETED\"",
    "\"TIME\"",
    "\"INTERVAL\"",
    "\"RANDOM\"",
    "\"FIFO\"",
    "\"CRESCENT\"",
    "\"DECREASING\"",
    "\"RESOURCE\"",
    "\"RESTRICT\"",
    "\"TASKPER\"",
    "\"USER\"",
    "\"[TCP]\"",
    "\"[TC]\"",
    "\"[NTS]\"",
    "\"[NTC]\"",
    "\"[PCU]\"",
    "\"[TCR]\"",
    "\"[PP]\"",
    "\"[LC]\"",
    "\"[TCT]\"",
    "\"[TCMT]\"",
    "\"[NTE]\"",
    "\"[MFE]\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"+\"",
    "\"(\"",
    "\")\"",
    "<inteiro>",
    "<real>",
    "<nome>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"*/\"",
    "<token of kind 45>",
    "<token of kind 46>",
    "<token of kind 47>",
    "\"/*\"",
    "\"//\"",
    "<invalido>",
    "\":\"",
    "\"[\"",
    "\"]\"",
  };

}
