/* Generated By:JavaCC: Do not edit this line. InterpretadorTokenManager.java */
package ispd.arquivo.interpretador.internal.iconic;

/** Token Manager. */
public class InterpretadorTokenManager implements InterpretadorConstants
{
private int contaErrosLex = 0;
private String erros = new String("");


public int encontrouErroLex()
{
        return contaErrosLex;
}

public void addErro(String msg)
{
        erros = erros+"\u005cn"+msg;
}

public String getErros()
{
        return erros;
}

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffff6L) != 0L)
         {
            jjmatchedKind = 21;
            return 14;
         }
         if ((active0 & 0x8L) != 0L)
         {
            jjmatchedKind = 20;
            return -1;
         }
         return -1;
      case 1:
         if ((active0 & 0x8L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 20;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0xffff6L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 1;
            return 14;
         }
         return -1;
      case 2:
         if ((active0 & 0x8L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 20;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0xefff2L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 21;
               jjmatchedPos = 2;
            }
            return 14;
         }
         if ((active0 & 0x10004L) != 0L)
            return 14;
         return -1;
      case 3:
         if ((active0 & 0x70L) != 0L)
            return 14;
         if ((active0 & 0xfff82L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 3;
            return 14;
         }
         return -1;
      case 4:
         if ((active0 & 0xffc02L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 4;
            return 14;
         }
         if ((active0 & 0x380L) != 0L)
            return 14;
         return -1;
      case 5:
         if ((active0 & 0xff002L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 5;
            return 14;
         }
         if ((active0 & 0xc00L) != 0L)
            return 14;
         return -1;
      case 6:
         if ((active0 & 0xe0002L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 6;
            return 14;
         }
         if ((active0 & 0x1f000L) != 0L)
            return 14;
         return -1;
      case 7:
         if ((active0 & 0xc0002L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 7;
            return 14;
         }
         if ((active0 & 0x20000L) != 0L)
            return 14;
         return -1;
      case 8:
         if ((active0 & 0x40000L) != 0L)
            return 14;
         if ((active0 & 0x80002L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 8;
            return 14;
         }
         return -1;
      case 9:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 9;
            return 14;
         }
         if ((active0 & 0x2L) != 0L)
            return 14;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0xc100L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x82000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x10L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x10404L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x822L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x20200L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa2_0(active0, 0x8L);
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x10904L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x420L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x10L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x49000L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x200L);
      case 83:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 87:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(2, 3);
         break;
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x210L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 68:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x8800L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 81:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 2;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x40100L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 69:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 5, 14);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 75:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 81:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 14);
         break;
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x25000L);
      case 84:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(3, 6, 14);
         return jjMoveStringLiteralDfa4_0(active0, 0x480L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 14);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 69:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 14);
         break;
      case 70:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 7, 14);
         break;
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 81:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 83:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x24000L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 69:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 10, 14);
         return jjMoveStringLiteralDfa6_0(active0, 0x84000L);
      case 77:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 11, 14);
         break;
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x2L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 85:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000L);
      case 86:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 15, 14);
         else if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 16, 14);
         break;
      case 69:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000L);
      case 71:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      case 78:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 14);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 79:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 14);
         break;
      case 82:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 14, 14);
         break;
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 69:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 17, 14);
         break;
      case 85:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000L);
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(8, 18, 14);
         break;
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000L);
      case 110:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(9, 1, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 76:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(10, 19, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 14;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xd0000484fffff8ffL & l) != 0L)
                  {
                     if (kind > 29)
                        kind = 29;
                     jjCheckNAdd(8);
                  }
                  else if ((0x2c00fb7a00000000L & l) != 0L)
                  {
                     if (kind > 20)
                        kind = 20;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(0, 2);
                  }
                  if (curChar == 35)
                     jjCheckNAddStates(3, 5);
                  break;
               case 14:
               case 2:
                  if ((0x2ffffb7a00000000L & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjCheckNAdd(2);
                  break;
               case 3:
                  if (curChar == 35)
                     jjCheckNAddStates(3, 5);
                  break;
               case 4:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               case 5:
                  if ((0x2400L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 6:
                  if (curChar == 10 && kind > 28)
                     kind = 28;
                  break;
               case 7:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if ((0xd0000484fffff8ffL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAdd(8);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddStates(0, 2);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(10);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 12:
                  if (curChar == 46)
                     jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjCheckNAdd(13);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  else if ((0x78000000f8000001L & l) != 0L)
                  {
                     if (kind > 20)
                        kind = 20;
                  }
                  else if ((0x8000000100000000L & l) != 0L)
                  {
                     if (kind > 29)
                        kind = 29;
                     jjCheckNAdd(8);
                  }
                  break;
               case 14:
                  if ((0x7ffffffeffffffffL & l) != 0L)
                  {
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAdd(2);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAddTwoStates(1, 2);
                  }
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if ((0x7ffffffeffffffffL & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjCheckNAdd(2);
                  break;
               case 4:
                  jjAddStates(3, 5);
                  break;
               case 8:
                  if ((0x8000000100000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAdd(8);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 8:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAdd(8);
                  break;
               case 4:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(3, 5);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   10, 11, 12, 4, 5, 7, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\122\157\165\156\144\122\157\142\151\156", "\115\101\121", "\55\55\55", 
"\114\115\101\121", "\122\105\104\105", "\111\116\105\124", "\106\120\114\124\106", 
"\103\101\122\107\101", "\124\122\101\103\105", "\115\105\123\124\122\105", 
"\122\101\116\104\117\115", "\120\117\111\123\123\117\116", "\105\123\103\122\101\126\117", 
"\103\114\125\123\124\105\122", "\103\117\116\105\103\124\101", "\115\101\121\125\111\116\101", 
"\124\127\117\123\124\101\107\105", "\127\117\122\113\121\125\105\125\105", 
"\105\130\120\117\116\105\116\103\111\101\114", null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffL, 
};
static final long[] jjtoSkip = {
   0x3f000000L, 
};
static final long[] jjtoSpecial = {
   0x20000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[14];
private final int[] jjstateSet = new int[28];
private final StringBuilder jjimage = new StringBuilder();
private StringBuilder image = jjimage;
private int jjimageLen;
private int lengthOfMatch;
protected char curChar;
/** Constructor. */
public InterpretadorTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public InterpretadorTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 14; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000700L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
            SkipLexicalActions(matchedToken);
         }
         else
            SkipLexicalActions(null);
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 29 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                addErro("Erro na linha "+input_stream.getEndLine()+". Caracter "+image+" n\u00c3\u00a3o \u00c3\u00a9 aceito.");
                contaErrosLex++;
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
