package ispd.motor.workload;

import ispd.motor.filas.RedeDeFilas;
import ispd.motor.filas.Tarefa;

import java.util.List;

/**
 * Represents a workload generation policy.
 */
public interface WorkloadGenerator {
    /**
     * Create a {@link Tarefa} list as currently configured, distributed
     * between the masters in the {@link RedeDeFilas} given.
     *
     * @param qn {@link RedeDeFilas} that will use the {@link Tarefa}s.
     * @return List of {@link Tarefa}s generated by this instance.
     */
    List<Tarefa> makeTaskList(RedeDeFilas qn);

    /**
     * @return the type of generator of this instance.
     * @see WorkloadGeneratorType
     */
    WorkloadGeneratorType getType();

    /**
     * @return human-readable string representation of how the generator is
     * currently configured.
     */
    @Override
    String toString();
}