/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfiguraMaquina.java
 *
 * Created on 28/12/2009, 16:02:00
 */

package ispd.Interface;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;
import java.util.ArrayList; 
import java.util.Vector;
/**
 *
 * @author Aldo Ianelo Guerra
 */
public class ConfiguraMaquina extends JDialog {

    /** Creates new form ConfiguraMaquina */
    public ConfiguraMaquina(Icone iconeAuxiliar,HashSet<String> listaNos) {
        initComponents(iconeAuxiliar,listaNos);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Icone iconeAuxiliar,HashSet<String> listaNos) {

        this.I = iconeAuxiliar;
        this.listaNos = listaNos;
        jLabeInicial = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelY = new javax.swing.JLabel();
        jLabelPoderComputacional = new javax.swing.JLabel();
        jLabelTaxaOcupacao = new javax.swing.JLabel();
        jTextFieldPoderComputacional = new javax.swing.JTextField();
        jLabelPoderCompucional1 = new javax.swing.JLabel();
        jTextFieldY = new javax.swing.JTextField();
        jLabelY1 = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jLabelX1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jRadioButtonEscravo = new javax.swing.JRadioButton();
        jRadioButtonMestre = new javax.swing.JRadioButton();
        jTextFieldTaxaOcupacao = new javax.swing.JTextField();
        jLabelTaxaOcupacao1 = new javax.swing.JLabel();
        jLabeInicial1 = new javax.swing.JLabel();
        jComboBoxAlgoritmos = new javax.swing.JComboBox();
        jLabeInicial2 = new javax.swing.JLabel();   
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEscravo = new javax.swing.JList(I.getNosEscalonaveis());
        jLabeInicial3 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setTitle("Machine icon configuration");
        setLocationRelativeTo(null);
	setModal(true);
        setResizable(false);

        jLabeInicial.setText("Configuration for the icon #: "+String.valueOf(I.getIdGlobal()));

        jLabelX.setText("X-coordinate:");

        jLabelNome.setText("Label:");

        jLabelY.setText("Y-coordinate:");

        jLabelPoderComputacional.setText("Computational power:");

        jLabelTaxaOcupacao.setText("Load factor:");

        jTextFieldPoderComputacional.setText(String.valueOf(I.getPoderComputacional()));
		if(jTextFieldPoderComputacional.getText()=="0.0"){
			jTextFieldPoderComputacional.setBackground(new java.awt.Color(255, 55, 55));
		}
		
        jLabelPoderCompucional1.setText("Mflop/s");

		jTextFieldY.setEditable(false);
        jTextFieldY.setText(String.valueOf(I.getNumY()));
        jTextFieldY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYActionPerformed(evt);
            }
        });

        jLabelY1.setText("px");

		jTextFieldX.setEditable(false);
        jTextFieldX.setText(String.valueOf(I.getNumX()));

        jLabelX1.setText("px");

        jTextFieldNome.setText(I.getNome());
	listaNos.remove(jTextFieldNome.getText());

		
		if(I.getMestre()){
			jRadioButtonEscravo.setSelected(false);
			jRadioButtonMestre.setSelected(true);
			setMinimumSize(new java.awt.Dimension(300, 500));
			setSize(new java.awt.Dimension(300, 500));
		}else{
			jRadioButtonEscravo.setSelected(true);
			jRadioButtonMestre.setSelected(false);
			jLabeInicial2.setVisible(false);
			jLabeInicial3.setVisible(false);
			
			jLabeInicial1.setVisible(false);
			jComboBoxAlgoritmos.setVisible(false);
			
			jListEscravo.setVisible(false);
			
			jScrollPane2.setVisible(false);
			setMinimumSize(new java.awt.Dimension(300, 250));
			setSize(new java.awt.Dimension(300, 250));
		}
		
        jRadioButtonEscravo.setText("Slave");
        jRadioButtonEscravo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEscravoActionPerformed(evt);
            }
        });

        jRadioButtonMestre.setText("Master");
        jRadioButtonMestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMestreActionPerformed(evt);
            }
        });

        jTextFieldTaxaOcupacao.setText(String.valueOf(I.getTaxaOcupacao()));
		
        jLabelTaxaOcupacao1.setText("%");

        jLabeInicial1.setText("Configuration for master nodes");

        jComboBoxAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" , "Round - Robin (RR)" , "Workqueue" }));
		if(I.getAlgoritmo()=="---"){
			jComboBoxAlgoritmos.setSelectedIndex(0);
		}
		if(I.getAlgoritmo()=="RoundRobin"){
			jComboBoxAlgoritmos.setSelectedIndex(1);
		}
		if(I.getAlgoritmo()=="Workqueue"){
			jComboBoxAlgoritmos.setSelectedIndex(2);
		}
        jComboBoxAlgoritmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlgoritmosActionPerformed(evt);
            }
        });
		if(jComboBoxAlgoritmos.getSelectedIndex()==0){
			jComboBoxAlgoritmos.setBackground(new java.awt.Color(255, 55, 55));
		}
        jLabeInicial2.setText("Scheduling algorithm:");

	jListEscravo.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
	List<Integer> escravos = I.getEscravos();
	Vector<Integer> listaConectados = I.getNosEscalonaveis();
	int tempIndices[] = new int[escravos.size()];
	int x = 0;
	for(int i:escravos){
		tempIndices[x] = listaConectados.indexOf(i);
		x++;
	}
	jListEscravo.setSelectedIndices(tempIndices);
	
        jScrollPane2.setViewportView(jListEscravo);

        jLabeInicial3.setText("slave nodes");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancel");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeInicial)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelX)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelY)
                            .addComponent(jLabelPoderComputacional)
                            .addComponent(jLabelTaxaOcupacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPoderComputacional, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPoderCompucional1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelY1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelX1))
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonEscravo)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonMestre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldTaxaOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTaxaOcupacao1))))
                    .addComponent(jLabeInicial1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeInicial2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabeInicial3)
                                    .addComponent(jComboBoxAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelX)
                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelX1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelY)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelY1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoderComputacional)
                    .addComponent(jLabelPoderCompucional1)
                    .addComponent(jTextFieldPoderComputacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTaxaOcupacao)
                    .addComponent(jTextFieldTaxaOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTaxaOcupacao1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMestre)
                    .addComponent(jRadioButtonEscravo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeInicial1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeInicial2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeInicial3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldYActionPerformed

    private void jRadioButtonEscravoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEscravoActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonEscravo.isSelected()){
			jRadioButtonMestre.setSelected(false);
			jLabeInicial2.setVisible(false);
			jLabeInicial3.setVisible(false);
			
			jLabeInicial1.setVisible(false);
			jComboBoxAlgoritmos.setVisible(false);
			
			jListEscravo.setVisible(false);
			
			jScrollPane2.setVisible(false);
			setMinimumSize(new java.awt.Dimension(300, 250));
			setSize(new java.awt.Dimension(300, 250));
		}else{
			jRadioButtonMestre.setSelected(true);
			jLabeInicial2.setVisible(true);
			jLabeInicial3.setVisible(true);
			
			jLabeInicial1.setVisible(true);
			jComboBoxAlgoritmos.setVisible(true);
			
			jListEscravo.setVisible(true);
			
			jScrollPane2.setVisible(true);
			setMinimumSize(new java.awt.Dimension(300, 500));
			setSize(new java.awt.Dimension(300, 500));
		}

}//GEN-LAST:event_jRadioButtonEscravoActionPerformed

    private void jRadioButtonMestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMestreActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonMestre.isSelected()){
			jRadioButtonEscravo.setSelected(false);
			jLabeInicial2.setVisible(true);
			jLabeInicial3.setVisible(true);
			
			jLabeInicial1.setVisible(true);
			jComboBoxAlgoritmos.setVisible(true);
			
			jListEscravo.setVisible(true);
			
			jScrollPane2.setVisible(true);
			setMinimumSize(new java.awt.Dimension(300, 500));
			setSize(new java.awt.Dimension(300, 500));
		}else{
			jRadioButtonEscravo.setSelected(true);
			jLabeInicial2.setVisible(false);
			jLabeInicial3.setVisible(false);
		
			jLabeInicial1.setVisible(false);
			jComboBoxAlgoritmos.setVisible(false);
			
			jListEscravo.setVisible(false);
			
			jScrollPane2.setVisible(false);
			setMinimumSize(new java.awt.Dimension(300, 250));
			setSize(new java.awt.Dimension(300, 250));
		}

}//GEN-LAST:event_jRadioButtonMestreActionPerformed

    private void jComboBoxAlgoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlgoritmosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlgoritmosActionPerformed


    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
	if(listaNos.contains(jTextFieldNome.getText())){
		JOptionPane.showMessageDialog(null,"There's already an icon named \'"+jTextFieldNome.getText()+"\'.\nPlease enter a different name.","WARNING",JOptionPane.PLAIN_MESSAGE);
	}else if(ValidaValores.validaNome(jTextFieldNome.getText()) && ValidaValores.validaDouble(jTextFieldPoderComputacional.getText()) && ValidaValores.validaDouble(jTextFieldTaxaOcupacao.getText()) ){
        	this.setVisible(false);
		if(jTextFieldNome.getText()!="")
			listaNos.add(jTextFieldNome.getText());
		I.setNome(jTextFieldNome.getText());
		Vector<Integer> listaConectados = I.getNosEscalonaveis();
		int indices[] = jListEscravo.getSelectedIndices();
		List<Integer> escravos = new ArrayList<Integer>();
		for(int i=0;i<indices.length;i++){
			escravos.add(listaConectados.get(indices[i]));
		}
		I.setEscravos(escravos);
		I.setPoderComputacional(Double.parseDouble(jTextFieldPoderComputacional.getText()));
		I.setTaxaOcupacao(Double.parseDouble(jTextFieldTaxaOcupacao.getText()));
		I.setPosition(Integer.parseInt(jTextFieldX.getText()),Integer.parseInt(jTextFieldY.getText()));
		if(jRadioButtonMestre.isSelected()){
			I.setMestre(true);
		}else{
			I.setMestre(false);
		}
		switch(jComboBoxAlgoritmos.getSelectedIndex()){
			case 0: I.setAlgoritmo("---"); break;
			case 1: I.setAlgoritmo("RoundRobin"); break;
			case 2: I.setAlgoritmo("Workqueue"); break;
		}
	}
	}//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxAlgoritmos;
    private javax.swing.JLabel jLabeInicial;
    private javax.swing.JLabel jLabeInicial1;
    private javax.swing.JLabel jLabeInicial2;
    private javax.swing.JLabel jLabeInicial3;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPoderCompucional1;
    private javax.swing.JLabel jLabelPoderComputacional;
    private javax.swing.JLabel jLabelTaxaOcupacao;
    private javax.swing.JLabel jLabelTaxaOcupacao1;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelX1;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JLabel jLabelY1;
    private javax.swing.JList jListEscravo;
    private javax.swing.JRadioButton jRadioButtonEscravo;
    private javax.swing.JRadioButton jRadioButtonMestre;
    private javax.swing.JScrollPane jScrollPane2;
    private JTextField jTextFieldNome;
    private JTextField jTextFieldPoderComputacional;
    private JTextField jTextFieldTaxaOcupacao;
    private JTextField jTextFieldX;
    private JTextField jTextFieldY;
    private HashSet<String> listaNos;
	private Icone I;
	// End of variables declaration//GEN-END:variables

}
