/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfiguraRede.java
 *
 * Created on 29/12/2009, 15:34:15
 */
package ispd.Interface;
import javax.swing.*;
import java.awt.*;
import java.util.*;
/**
 *
 * @author Aldo Ianelo Guerra
 */
public class ConfiguraRede extends JDialog {

    /** Creates new form ConfiguraRede */
    public ConfiguraRede(Icone iAux,HashSet<String> listaNos) {
        initComponents(iAux,listaNos);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Icone iAux,HashSet<String> listaNos) {

	this.listaNos = listaNos;
        jLabeInicial = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldX = new javax.swing.JTextField();
        jLabelX = new javax.swing.JLabel();
        jLabelX1 = new javax.swing.JLabel();
        jLabelY1 = new javax.swing.JLabel();
        jTextFieldY = new javax.swing.JTextField();
        jLabelY = new javax.swing.JLabel();
        jLabelBanda = new javax.swing.JLabel();
        jTextFieldBanda = new javax.swing.JTextField();
        jLabelBanda1 = new javax.swing.JLabel();
        jLabelTaxaOcupacao1 = new javax.swing.JLabel();
        jTextFieldTaxaOcupacao = new javax.swing.JTextField();
        jLabelTaxaOcupacao = new javax.swing.JLabel();
        jLabelLatencia = new javax.swing.JLabel();
        jTextFieldLatencia = new javax.swing.JTextField();
        jLabelLatencia1 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelX2 = new javax.swing.JLabel();
        jLabelY2 = new javax.swing.JLabel();
        jTextFieldY1 = new javax.swing.JTextField();
        jLabelY3 = new javax.swing.JLabel();
        jTextFieldX1 = new javax.swing.JTextField();
        jLabelX3 = new javax.swing.JLabel();
		this.I = iAux;

        setTitle("Network icon configuration");
        setLocationRelativeTo(null);
		setResizable(false);
		setModal(true);

        jLabeInicial.setText("Configuration for the network #: "+String.valueOf(I.getIdGlobal()));

        jLabelNome.setText("Label:");

        jTextFieldNome.setText(I.getNome());
	listaNos.remove(jTextFieldNome.getText());

		jTextFieldX.setEditable(false);
        jTextFieldX.setText(String.valueOf(I.getNumX()));
        jTextFieldX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXActionPerformed(evt);
            }
        });

        jLabelX.setText("X1-coordinate:");

        jLabelX1.setText("px");

        jLabelY1.setText("px");

		jTextFieldY.setEditable(false);
        jTextFieldY.setText(String.valueOf(I.getNumY()));
        jTextFieldY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYActionPerformed(evt);
            }
        });

        jLabelY.setText("Y1-coordinate:");

        jLabelBanda.setText("Bandwidth:");

        jTextFieldBanda.setText(String.valueOf(I.getBanda()));

        jLabelBanda1.setText("Mb/s");

        jLabelTaxaOcupacao1.setText("%");

        jTextFieldTaxaOcupacao.setText(String.valueOf(I.getTaxaOcupacao()));

        jLabelTaxaOcupacao.setText("Load factor:");

        jLabelLatencia.setText("Latency");

        jTextFieldLatencia.setText(String.valueOf(I.getLatencia()));

        jLabelLatencia1.setText("s");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancel");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelX2.setText("X2-coordinate:");

        jLabelY2.setText("Y2-coordinate:");

		jTextFieldY1.setEditable(false);
        jTextFieldY1.setText(String.valueOf(I.getNumPreY()));
        jTextFieldY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldY1ActionPerformed(evt);
            }
        });

        jLabelY3.setText("px");

		jTextFieldX1.setEditable(false);
        jTextFieldX1.setText(String.valueOf(I.getNumPreX()));
        jTextFieldX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldX1ActionPerformed(evt);
            }
        });

        jLabelX3.setText("px");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeInicial)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelX)
                                    .addComponent(jLabelY)
                                    .addComponent(jLabelX2)
                                    .addComponent(jLabelY2)
                                    .addComponent(jLabelBanda)
                                    .addComponent(jLabelTaxaOcupacao)
                                    .addComponent(jLabelLatencia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldY, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldX, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldLatencia, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldTaxaOcupacao, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldBanda, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldX1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldY1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelX1)
                                            .addComponent(jLabelY1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelX3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelY3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelBanda1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelTaxaOcupacao1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelLatencia1)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelX)
                    .addComponent(jLabelY1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelY)
                    .addComponent(jLabelX1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelX2)
                    .addComponent(jLabelX3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelY2)
                    .addComponent(jLabelY3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBanda)
                    .addComponent(jLabelBanda1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTaxaOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTaxaOcupacao)
                    .addComponent(jLabelTaxaOcupacao1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLatencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLatencia)
                    .addComponent(jLabelLatencia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldYActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
	if(listaNos.contains(jTextFieldNome.getText()) && jTextFieldNome.getText()!=""){
		JOptionPane.showMessageDialog(null,"There's already an icon named \'"+jTextFieldNome.getText()+"\'.\nPlease enter a different name.","WARNING",JOptionPane.PLAIN_MESSAGE);
	}else if(ValidaValores.validaNome(jTextFieldNome.getText()) && ValidaValores.validaDouble(jTextFieldBanda.getText()) && ValidaValores.validaDouble(jTextFieldTaxaOcupacao.getText()) && ValidaValores.validaDouble(jTextFieldLatencia.getText()) ){
        	this.setVisible(false);
		I.setNome(jTextFieldNome.getText());
		listaNos.add(jTextFieldNome.getText());
		I.setLatencia(Double.parseDouble(jTextFieldLatencia.getText()));
		I.setBanda(Double.parseDouble(jTextFieldBanda.getText()));
		I.setTaxaOcupacao(Double.parseDouble(jTextFieldTaxaOcupacao.getText()));
		I.setPosition(Integer.parseInt(jTextFieldX.getText()),Integer.parseInt(jTextFieldY.getText()));		
		I.setPrePosition(Integer.parseInt(jTextFieldX1.getText()),Integer.parseInt(jTextFieldY1.getText()));
	}
}//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldY1ActionPerformed

    private void jTextFieldXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldXActionPerformed

    private void jTextFieldX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabeInicial;
    private javax.swing.JLabel jLabelLatencia;
    private javax.swing.JLabel jLabelLatencia1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelBanda1;
    private javax.swing.JLabel jLabelBanda;
    private javax.swing.JLabel jLabelTaxaOcupacao;
    private javax.swing.JLabel jLabelTaxaOcupacao1;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelX1;
    private javax.swing.JLabel jLabelX2;
    private javax.swing.JLabel jLabelX3;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JLabel jLabelY1;
    private javax.swing.JLabel jLabelY2;
    private javax.swing.JLabel jLabelY3;
    private javax.swing.JTextField jTextFieldLatencia;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldBanda;
    private javax.swing.JTextField jTextFieldTaxaOcupacao;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldX1;
    private javax.swing.JTextField jTextFieldY;
    private javax.swing.JTextField jTextFieldY1;
    private HashSet<String> listaNos;
	private Icone I;
    // End of variables declaration//GEN-END:variables

}
