/* Generated By:JavaCC: Do not edit this line. SimGridConstants.java */
package ispd.InterpretadorExterno.SimGrid;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimGridConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int XML = 1;
  /** RegularExpression Id. */
  int CPU = 2;
  /** RegularExpression Id. */
  int NAME = 3;
  /** RegularExpression Id. */
  int BANDWIDTH = 4;
  /** RegularExpression Id. */
  int LATENCY = 5;
  /** RegularExpression Id. */
  int ROUTE = 6;
  /** RegularExpression Id. */
  int SRC = 7;
  /** RegularExpression Id. */
  int DST = 8;
  /** RegularExpression Id. */
  int ROUTE_ELEMENT = 9;
  /** RegularExpression Id. */
  int PROCESS = 10;
  /** RegularExpression Id. */
  int NETWORK_LINK = 11;
  /** RegularExpression Id. */
  int HOST = 12;
  /** RegularExpression Id. */
  int FUNCTION = 13;
  /** RegularExpression Id. */
  int ARGUMENT = 14;
  /** RegularExpression Id. */
  int VALUE = 15;
  /** RegularExpression Id. */
  int POWER = 16;
  /** RegularExpression Id. */
  int MASTER = 17;
  /** RegularExpression Id. */
  int SLAVE = 18;
  /** RegularExpression Id. */
  int TASKSOURCE = 19;
  /** RegularExpression Id. */
  int SLAVECOMM = 20;
  /** RegularExpression Id. */
  int RELOADHOST = 21;
  /** RegularExpression Id. */
  int FORWARDERSCHEDULER = 22;
  /** RegularExpression Id. */
  int FORWARDERNODE = 23;
  /** RegularExpression Id. */
  int FORWARDERCOMM = 24;
  /** RegularExpression Id. */
  int PLATFORM_DESCRIPTION = 25;
  /** RegularExpression Id. */
  int VERSION = 26;
  /** RegularExpression Id. */
  int letra = 27;
  /** RegularExpression Id. */
  int digito = 28;
  /** RegularExpression Id. */
  int ponto = 29;
  /** RegularExpression Id. */
  int barra = 30;
  /** RegularExpression Id. */
  int exclamacao = 31;
  /** RegularExpression Id. */
  int interrogacao = 32;
  /** RegularExpression Id. */
  int menor = 33;
  /** RegularExpression Id. */
  int maior = 34;
  /** RegularExpression Id. */
  int igual = 35;
  /** RegularExpression Id. */
  int apostrofo = 36;
  /** RegularExpression Id. */
  int aspas = 37;
  /** RegularExpression Id. */
  int especiais = 38;
  /** RegularExpression Id. */
  int invalido = 39;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"xml\"",
    "\"cpu\"",
    "\"name\"",
    "\"bandwidth\"",
    "\"latency\"",
    "\"route\"",
    "\"src\"",
    "\"dst\"",
    "\"route_element\"",
    "\"process\"",
    "\"network_link\"",
    "\"host\"",
    "\"function\"",
    "\"argument\"",
    "\"value\"",
    "\"power\"",
    "\"master\"",
    "\"slave\"",
    "\"tasksource\"",
    "\"slavecomm\"",
    "\"reloadhost\"",
    "\"forwarderscheduler\"",
    "\"forwardernode\"",
    "\"forwardercomm\"",
    "\"platform_description\"",
    "\"version\"",
    "<letra>",
    "<digito>",
    "\".\"",
    "\"/\"",
    "\"!\"",
    "\"?\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<especiais>",
    "<invalido>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<!\"",
    "\">\"",
    "<token of kind 47>",
  };

}
